        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep  2 10:33:28 2015
        MODULE ALLOC_STATUS__genmod
          INTERFACE 
            SUBROUTINE ALLOC_STATUS(MSG,PROCESSNAME)
              CHARACTER(LEN=80), INTENT(IN) :: MSG
              CHARACTER(LEN=24), INTENT(IN) :: PROCESSNAME
            END SUBROUTINE ALLOC_STATUS
          END INTERFACE 
        END MODULE ALLOC_STATUS__genmod
