        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep  2 10:33:28 2015
        MODULE FFT_TO_LEGENDRE__genmod
          INTERFACE 
            SUBROUTINE FFT_TO_LEGENDRE(FFT_ARRAY,LEGENDRE_ARRAY)
              REAL(KIND=8), INTENT(IN) :: FFT_ARRAY(:,:,:)
              REAL(KIND=8), INTENT(INOUT) :: LEGENDRE_ARRAY(:,:,:)
            END SUBROUTINE FFT_TO_LEGENDRE
          END INTERFACE 
        END MODULE FFT_TO_LEGENDRE__genmod
