        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep  1 16:25:06 2015
        MODULE GRID_TO_FFT__genmod
          INTERFACE 
            SUBROUTINE GRID_TO_FFT(GRID_ARRAY,FFT_ARRAY)
              REAL(KIND=8), INTENT(IN) :: GRID_ARRAY(:,:,:)
              REAL(KIND=8), INTENT(INOUT) :: FFT_ARRAY(:,:,:)
            END SUBROUTINE GRID_TO_FFT
          END INTERFACE 
        END MODULE GRID_TO_FFT__genmod
