        !COMPILER-GENERATED INTERFACE MODULE: Wed Sep  2 10:58:41 2015
        MODULE LEGENDRE_TO_FFT__genmod
          INTERFACE 
            SUBROUTINE LEGENDRE_TO_FFT(LEGENDRE_ARRAY,FFT_ARRAY)
              REAL(KIND=8), INTENT(IN) :: LEGENDRE_ARRAY(:,:,:)
              REAL(KIND=8), INTENT(INOUT) :: FFT_ARRAY(:,:,:)
            END SUBROUTINE LEGENDRE_TO_FFT
          END INTERFACE 
        END MODULE LEGENDRE_TO_FFT__genmod
