        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep  1 16:25:07 2015
        MODULE LEGENDRE_TO_SPECTRAL__genmod
          INTERFACE 
            SUBROUTINE LEGENDRE_TO_SPECTRAL(LEGENDRE_ARRAY,             &
     &SPECTRAL_ARRAY)
              REAL(KIND=8), INTENT(IN) :: LEGENDRE_ARRAY(:,:,:)
              REAL(KIND=8), INTENT(INOUT) :: SPECTRAL_ARRAY(:,:,:)
            END SUBROUTINE LEGENDRE_TO_SPECTRAL
          END INTERFACE 
        END MODULE LEGENDRE_TO_SPECTRAL__genmod
