        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep  1 16:25:07 2015
        MODULE SPECTRAL_TO_LEGENDRE__genmod
          INTERFACE 
            SUBROUTINE SPECTRAL_TO_LEGENDRE(SPECTRAL_ARRAY,             &
     &LEGENDRE_ARRAY)
              REAL(KIND=8), INTENT(IN) :: SPECTRAL_ARRAY(:,:,:)
              REAL(KIND=8), INTENT(INOUT) :: LEGENDRE_ARRAY(:,:,:)
            END SUBROUTINE SPECTRAL_TO_LEGENDRE
          END INTERFACE 
        END MODULE SPECTRAL_TO_LEGENDRE__genmod
